version: '3.9'

services:
  # MongoDB Container
  mongodb:
    container_name: xpense_mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongodb:/data/db

  # Node Container
  node:
    container_name: xpense_node_container
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/xpense
    environment:
      - PORT=3000
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongodb: {}
